### Send POST request with json body
POST {{host}}/todos/
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "created_by": 2,
  "assignee": 1,
  "description": "Make the bed"
}