### Send POST request with json body
PUT {{host}}/todos/{{last_todo_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
  "id": {{last_todo_id}},
  "created_by": 2,
  "assignee": 1,
  "description": "Go to the gym",
  "created_at": "2021-02-18T21:54:42.123Z",
  "updated_at": "2021-02-18T21:54:42.123Z"
}