### Send POST request with json body
POST {{host}}/refresh
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "refresh_token": {{refresh_token}}
}

> {%
client.global.set("access_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);
%}

