### Send POST request with json body
POST {{host}}/users/register
Content-Type: application/json

{
  "username": "gogolev",
  "password": "gogolev",
  "password_confirmation": "gogolev",
  "email": "lehente@bk.ru"
}

### Send POST request with json body
POST {{host}}/users/register
Content-Type: application/json

{
  "username": "goga",
  "password": "goga",
  "password_confirmation": "goga",
  "email": "lehente2000@gmail.com"
}
