### Send POST request with json body
POST http://localhost:3000/users/refresh
Content-Type: application/json

{
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTgwNjc2NzksInVzZXJfaWQiOjF9.tabrN221WHmJYVFJ5_Ko0eHEgldYqgTUSNOKITs0LAM"
}

