### Send POST request with json body
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "epopov",
  "password": "epopov",
  "password_confirmation": "epopov",
  "email": "epopov@example.com"
}

### Send POST request with json body
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "epopov",
  "password": "epopov",
  "password_confirmation": "epopov",
  "email": "epopov@example.com"
}
