### Send PUT request with json body
PUT http://localhost:3000/users/update-password
Content-Type: application/json

{
  "id": 1,
  "old_password": "epopov",
  "password": "popov",
  "password_confirmation": "popov"
}

